[package]
name = "ClawBrowser"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.13.1"
tokio = { version = "1.49.0", features = ["full"] }
scraper = "0.22.0"
ego-tree = "0.10.0"
cssparser = "0.34.0"
selectors = "0.26.0"
